name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d9e2f3f6f628032f16f9a5b263265470702ddc1b17a9856ce5667797524c206"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
