name = "Sodium Vanilla"
author = "0_byte"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "263f6d53aaba47ce35ea3d13e9345371bfbc790e7756262a84ba5bf0db395b47"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
